apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ include "helm-pattern.fullname" . }}-script-job-env
  labels:
    {{- include "helm-pattern.labels" . | nindent 4 }}
    component: init
data:
  {{- if .Values.jobImage.environment }}
  {{- range $key, $val := .Values.jobImage.environment }}
  {{ $key }}: {{ tpl $val $ | quote }}
  {{- end }}
  {{- end }}
  HELM_RELEASE: "{{ .Release.Name }}"
  NAMESPACE: "{{ .Release.Namespace }}"
