apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ include "helm-pattern.fullname" . }}-script-job-volume
  labels:
    {{- include "helm-pattern.labels" . | nindent 4 }}
    component: init
data:
{{ (.Files.Glob "bin/*.*").AsConfig | indent 2 }}
